function xxxErase(src,event,fig)
%xxxErase - erase lines by setting values to zero. This won't change the
%size of the image, or annotations, but removes the lines that typically
%plague Waters files.

% Get the guidata
dpn = guidata(fig.fig);
if isempty(dpn)
    return
end

% Draw the window and the controls
[erase] = eraseWindow(src,event,fig);

% Set the callback for the finish button / window close
set(erase.do,'Callback',{@xxxEraseFunction,fig,erase});

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = eraseWindow(~,~,fig)
% Window with the little options for manipulating the figure...

% This is where we draw everything
parent = fig.pan2;

fS = 14;

% Heading
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','Erase Mode',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);

% Number of lines to erase
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.595+0.2 0.5 0.1],...
    'Style','text',...
    'String','Number of lines',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.lines = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.66+0.2 0.46 0.04],...
    'Style','edit',...
    'String','5',...
    'FontSize',fS);

% Value to set to
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.595+0.15 0.5 0.1],...
    'Style','text',...
    'String','Replacement value',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.value = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.66+0.15 0.46 0.04],...
    'Style','edit',...
    'String','0',...
    'FontSize',fS);

% A button to 'do' what we wanted...
man.do = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0 0.9 0.1],...
    'Style','pushbutton',...
    'String','Erase',...
    'FontSize',16,...
    'BackgroundColor',[0 156 29]/256,...
    'ForegroundColor',[0 0 0]);

% Some text to explain the schtick
message = ['This function is here to help remove lines, which are '...
    'very common in Waters data.  Note that this function doesn''t '...
    'delete the lines.  Instead it just sets their values to that ' ...
    'specified in the box.  Also, please note that this cannot be ' ...
    'undone - it is a permanent change.'];
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.45 0.9 0.2],...
    'Style','text',...
    'String',message,...
    'FontSize',12,...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%