function xxxHistoVis(src,event,fig)
%xxxErase - erase lines by setting values to zero. This won't change the
%size of the image, or annotations, but removes the lines that typically
%plague Waters files.

% Get the guidata
dpn = guidata(fig.fig);
if isempty(dpn)
    return
end

% Draw the window and the controls
[man] = histoWindow(src,event,fig);

% Set the callback for the finish button / window close
set(man.trans,'Callback',{@xxxHistoChange,fig,man});
set(man.value,'Callback',{@xxxHistoChange,fig,man});

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = histoWindow(~,~,fig)
% Window with the little options for manipulating the figure...

% This is where we draw everything
parent = fig.pan2;

fS = 14;

% Heading
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','Histology Overlay',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);

% Number of lines to erase
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.8 0.75 0.05],...
    'Style','text',...
    'String','Transparency',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.trans = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.75 0.9 0.05],...
    'Style','slider',...
    'Min',0,...
    'Max',100,...
    'SliderStep',[0.01 0.1],...
    'FontSize',fS);
man.value = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.775 0.8225 0.175 0.025],...
    'Style','edit',...
    'String','50',...
    'FontSize',fS);

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%