function xxxLipidFamilyWindow(src,event,fig)
%dpnSegmentationWindow - draw a window to allow us to play around with
%various segmentation things...

% Get the guidata
dpn = guidata(fig.fig);
if isempty(dpn)
    return
end

% Draw the side panel
[man] = familyWindow(src,event,fig);

% Draw different windows depending on the analysis mode.  And then also
% set the callbacks for the functions...
switch dpn.mode
    case 'dual'
        
        % Set callback to perform annotation
        set(man.annotate,'Callback',{@xxxLipidFamilyAnnotate,fig,man,'dual'});
        
        % Callback for the fusion options
        set(man.do,'Callback',{@xxxLipidFamilyDraw,fig,man});
        
    case 'single'
       
end

% If there are already annotated features, then we can just display them in
% the family box
if isfield(dpn.d1,'anno')    
    if strcmp(dpn.mode,'dual')
        allFam = unique([dpn.d1.anno.fam(:); dpn.d2.anno.fam(:)]);
    else
        allFam = unique(dpn.d1.anno.fam(:));
    end    
    set(man.family,'String',allFam,'Value',1);    
end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = familyWindow(src,event,fig)
% This is the revised version for fused data - won't implement this version
% for the single mode toolbox just yet.  Aim to make it consistent with the
% QDS menu bar.

% Define a font size
fS = 14;

% Where should we draw everything
parent = fig.pan2;

% Opening text
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','Lipid Families',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);

% Annotate the lipids button
man.annotate = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.85 0.45 0.05],...
    'Style','pushbutton',...
    'String','Annotate',...
    'FontSize',16,...
    'BackgroundColor',[0 156 29]/256,...
    'ForegroundColor',[0 0 0]);

% ppm tolerance
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.55 0.85-0.065 0.2 0.1],...
    'Style','text',...
    'String','± ppm = ',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.ppm = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.75 0.85 0.2 0.04],...
    'Style','edit',...
    'String','10',...
    'FontSize',fS);

% Families
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.6 0.5 0.1],...
    'Style','text',...
    'String','Family',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.family = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.6 0.5 0.1],...
    'Style','popupmenu',...
    'String',{'Unknown'},...
    'Value',1,...
    'FontSize',fS);

% Suppress high intensities
man.suppress = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.55 0.9 0.025],...
    'Style','checkbox',...
    'String','Suppress high intensities?',...
    'Value',0,...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);

% Do you want to log intensities
man.log = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.525 0.9 0.025],...
    'Style','checkbox',...
    'String','Log images?',...
    'Value',0,...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);


% A button to draw the images
man.do = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.275 0.9 0.05],...
    'Style','pushbutton',...
    'String','Draw',...
    'FontSize',16,...
    'BackgroundColor',[0 156 29]/256,...
    'ForegroundColor',[0 0 0]);


end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
