function dpnCoreg(src,event,fig)
%dpnCoreg - perform image coregistration in a fashion.

% Get the guidata
dpn = guidata(fig.fig);
if isempty(dpn)
    return
end

% Need to decide if we have single ion mode or dual ion mode
if strcmp(dpn.mode,'dual')
    labels = {'Positive';'Negative'};
else
    labels = {'Original';'Otsu'};
end

% Draw the window and the controls
[cor] = coregWindow(src,event,fig,labels);

% Callbacks for optical image rotation
set(cor.rot1,'Callback',{@dpnOptRotate,fig,cor,+1});
set(cor.rot2,'Callback',{@dpnOptRotate,fig,cor,-1});

% Callback for MSI image rotation
set(cor.rotMSI,'Callback',{@xxxRotateMSI,fig,cor,-1});

% For MS image thresholding...
set(cor.listMS,'Callback',{@dpnOtsuMS,fig,cor});
set(cor.slideMS,'Callback',{@dpnOtsuMS,fig,cor});

% For OP image thresholding...
set(cor.listOP,'Callback',{@dpnOtsuOP,fig,cor});
set(cor.slideOP,'Callback',{@dpnOtsuOP,fig,cor});

% Final coregistration go go go
set(cor.do,'Callback',{@dpnCoregPerform,fig,cor});
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = coregWindow(~,~,fig,labels)
% Window with the little options for manipulating the figure...

% Set the parent
parent = fig.pan2;


% Opical image rotation...
man.rot1 = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.85 0.4 0.1],...
    'Style','pushbutton',...
    'String','OPT -90',...
    'FontSize',16,...
    'BackgroundColor',[19 227 237]/256);
man.rot2 = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.55 0.85 0.4 0.1],...
    'Style','pushbutton',...
    'String','OPT +90',...
    'FontSize',16,...
    'BackgroundColor',[19 227 237]/256);

% Optical image to be shown...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','Optical',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);
man.listOP = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.1 0.75 0.8 0.075],...
    'Style','listbox',...
    'String',{'Original';'Otsu'},...
    'Value',1,...
    'FontSize',16);%'Min',1,...'Max',3);

% Slider for image thresholding...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.1 0.675 0.8 0.05],...
    'Style','text',...
    'String','Threshold',...
    'FontSize',16,...
    'BackgroundColor',[1 1 1]);
man.slideOP = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.1 0.6 0.8 0.1],...
    'Style','slider',...
    'Min',1,...
    'Max',20,...
    'SliderStep',[0.05 0.1],...
    'Value',2,...
    'FontSize',16);%'Min',1,...'Max',3);

% Ions to be shown...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.5 1 0.05],...
    'Style','text',...
    'String','Mass Spec',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);
man.listMS = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.1 0.425 0.8 0.075],...
    'Style','listbox',...
    'String',labels,...
    'Value',1,...
    'FontSize',16);%'Min',1,...'Max',3);

% Slider for image thresholding...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.1 0.35 0.8 0.05],...
    'Style','text',...
    'String','Threshold',...
    'FontSize',16,...
    'BackgroundColor',[1 1 1]);
man.slideMS = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.1 0.275 0.8 0.1],...
    'Style','slider',...
    'Min',1,...
    'Max',20,...
    'SliderStep',[0.05 0.1],...
    'Value',2,...
    'FontSize',16);%'Min',1,...'Max',3);

% Supress the high intensity pixels?
man.skip = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.15 0.5 0.025],...
    'Style','checkbox',...
    'Value',0,...
    'String','Iter = 1',...
    'FontSize',12,...
    'Enable','on',...
    'BackgroundColor',[1 1 1]);


% NUCLEAR OPTION - rotate the imzML image through 90 degrees. Typically not
% recommended but an option for skin analysis by Josh
% Opical image rotation...
man.rotMSI = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.1 0.3 0.3 0.025],...
    'Style','pushbutton',...
    'String','MSI +90',...
    'FontSize',16,...
    'BackgroundColor',[222 91 91]/256);



% A button to 'do' what we wanted...
man.do = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0 0.9 0.1],...
    'Style','pushbutton',...
    'String','Co-register',...
    'FontSize',16,...
    'BackgroundColor',[0 156 29]/256,...
    'ForegroundColor',[0 0 0]);

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%