function [ fig ] = dpnDraw
%dpnDraw - main function for drawing the window and the axes

f0 = findobj('Tag','desiposneg');
close(f0);

% Determine what layout is to be drawn on initialisation
fig.style = 'simple'; % simple | detail
locn = dpnLocations(fig.style);


fig.fig = figure('Name','DESI Pos / Neg',...
    'Units','normalized',...
    'Position',[0.05 0.2 0.6 0.6],...
    'Tag','desiposneg',...
    'Color','white');

try
    set(fig.fig,'NumberTitle','off');
catch
    set(fig.fig,'Number','none');
end

% We need to have two panels - one for the menus and another for the axes
% and stuff
fig.pan1 = uipanel('Parent',fig.fig,...
    'Units','normalized',...
    'Position',[0.2 0 0.8 1],...
    'BackgroundColor',[1 1 1]);

fig.pan2 = uipanel('Parent',fig.fig,...
    'Units','normalized',...
    'Position',[0 0 0.2 1],...
    'BackgroundColor',[1 1 1]);

% Three axes - opt, ms1, ms2
fig.ax.opt(1) = axes('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.opt.ax,...
    'XTick',[],...
    'YTick',[],...
    'Box','on',...
    'Visible','on');
fig.ax.opt(2) = imagesc(ones(10,10));
title(fig.ax.opt(1),'Optical');

fig.ax.ms1(1) = axes('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.ms1.ax,...
    'XTick',[],...
    'YTick',[],...
    'Box','on',...
    'Visible','on');
fig.ax.ms1(2) = imagesc(ones(10,10));
title(fig.ax.ms1(1),'Positive');

fig.ax.ms2(1) = axes('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.ms2.ax,...
    'XTick',[],...
    'YTick',[],...
    'Box','on',...
    'Visible','on');
fig.ax.ms2(2) = imagesc(ones(10,10));
title(fig.ax.ms2(1),'Negative');

fig.ax.fu(1) = axes('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.fu.ax,...
    'XTick',[],...
    'YTick',[],...
    'Box','on',...
    'Visible','on');
fig.ax.fu(2) = imagesc(ones(10,10));
title(fig.ax.fu(1),'Fused');

% Want to draw a lot of the extra axes here too
fig.ax.sp(1) = axes('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.sp.ax,...
    'XTick',[],...
    'YTick',[],...
    'Box','on',...
    'Visible',locn.sp.vis,...
    'LineWidth',5,...
    'TickLength',[0 0]);

% And another for showing stuff like PCA of annotated pixels
fig.ax.mv(1) = axes('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.mv.ax,...
    'XTick',[],...
    'YTick',[],...
    'Box','on',...
    'Visible',locn.mv.vis,...
    'LineWidth',5,...
    'TickLength',[0 0]);


% Define the colourmap
colormap(redbluecmap);

set([fig.ax.opt(1) fig.ax.ms1(1) fig.ax.ms2(1) fig.ax.fu(1)],...
    'XTick',[],...
    'YTick',[],...
    'LineWidth',5,...
    'TickLength',[0 0]);

% Titles for permanency
fig.titOpt = uicontrol('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.opt.lab1,...
    'Style','text',...
    'String','Optical',...
    'FontSize',12,...
    'FontWeight','bold',...
    'BackgroundColor','white');
fig.titPos = uicontrol('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.ms1.lab1,...
    'Style','text',...
    'String','Positive',...
    'FontSize',12,...
    'FontWeight','bold',...
    'BackgroundColor','white');
fig.titNeg = uicontrol('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.ms2.lab1,...
    'Style','text',...
    'String','Negative',...
    'FontSize',12,...
    'FontWeight','bold',...
    'BackgroundColor','white');

% Boxes somewhere for the pos / neg axes to tell the user what they are
% looking at. SUch as PCA image of PC1...
fig.txtOpt = uicontrol('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.opt.lab2,...
    'Style','text',...
    'String','---',...
    'FontSize',12,...
    'FontWeight','bold',...
    'BackgroundColor','white');
fig.txtPos = uicontrol('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.ms1.lab2,...
    'Style','text',...
    'String','---',...
    'FontSize',12,...
    'FontWeight','bold',...
    'BackgroundColor','white');
fig.txtNeg = uicontrol('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.ms2.lab2,...
    'Style','text',...
    'String','---',...
    'FontSize',12,...
    'FontWeight','bold',...
    'BackgroundColor','white');



% Toolbar required
[fig] = dpnDrawToolbar(fig);

end

