function dpnManipulateMS(~,~,fig,mode)
%dpnManipulateMS - edit the MS ion image...


% Get the guidata
dpn = guidata(fig.fig);
if isempty(dpn)
    return
end

% Determine what the defaults are, or whether the image has already been
% manipulated; and if so then draw those options. Otherwise use the
% defaults...
if isfield(dpn.d1,'opts') && strcmp(mode,'pos')
    defs = dpn.d1.opts;
    allmz = dpn.d1.mz;
elseif isfield(dpn,'d2') && isfield(dpn.d2,'opts') && strcmp(mode,'neg')
    defs = dpn.d2.opts;
    allmz = dpn.d2.mz;
else
    defs.ions = [600; 900];
    defs.doLog = 0;
    allmz = dpn.d1.mz;
end

if size(allmz,1) > size(allmz,2)
    allmz = allmz';
end

% Now here perhaps we could draw an options window for maniulating the
% image.  We need to be able to perform: ion image selection and
% interpolation changes
[man] = manipulateWindow([],[],mode,fig,defs,[0 allmz]);

% Set the callbacks...
set(man.do,'Callback',{@dpnManipulateCallback,fig,mode,man});

% This is only currently for single mode
if strcmp(dpn.mode,'single')
    set(man.list,'Callback',{@dpnIonImageScroll,fig,mode,man});
    set(man.rgb2opt,'Callback',{@desiRGB2Opt,fig});
else
    set(man.list,'Visible','off');
    set(man.rgb2opt,'Visible','off');
end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = manipulateWindow(~,~,mode,fig,defs,allmz)
% Window with the little options for manipulating the figure...

% Where to actually draw it
parent = fig.pan2;

% Reshape the ions to make it look the same, i.e. [n x 2]
a = 1:2:numel(defs.ions)-1;
b = 2:2:numel(defs.ions);
defs.ions = [defs.ions(a,1) defs.ions(b,1)];

% Ions to be shown...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','m/z ',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);
man.ion = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.1 0.75 0.8 0.2],...
    'Style','edit',...
    'String',num2str(defs.ions),...
    'FontSize',16,...
    'Max',5,...
    'Min',1);
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.55 1 0.2],...
    'Style','text',...
    'String',['Enter m/z ranges in the box above. ' char(10)...
        'For multiple ranges, use separate lines. '...
        char(10) 'e.g. 645 655 // 885 886'],...
    'FontSize',12,...
    'BackgroundColor',[1 1 1]);

% Logarithm
if ~isfield(defs,'doLog')
    defs.doLog = 0;
end
man.doLog = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.63 0.9 0.025],...
    'Style','checkbox',...
    'Value',defs.doLog,...
    'String','Log transformation?',...
    'FontSize',16,...
    'Enable','on',...
    'BackgroundColor',[1 1 1]);

% Supress the high intensity pixels?
man.suppress = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.605 0.9 0.025],...
    'Style','checkbox',...
    'Value',0,...
    'String','Suppress high intensities?',...
    'FontSize',16,...
    'Enable','on',...
    'BackgroundColor',[1 1 1]);

% Supress the high intensity pixels?
man.showInterp = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.655 0.9 0.025],...
    'Style','checkbox',...
    'Value',0,...
    'String','Hide interpolated pixels?',...
    'FontSize',16,...
    'Enable','on',...
    'BackgroundColor',[1 1 1]);

% This is all the extra stuff for the ion images
man.list(1) = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.07 0.3 0.3],...
    'Style','listbox',...
    'String',num2str(allmz'),...
    'FontSize',16,...
    'Max',5,...
    'Min',1,...
    'BackgroundColor',[1 0.8 0.8]);
man.list(2) = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.35 0.07 0.3 0.3],...
    'Style','listbox',...
    'String',num2str(allmz'),...
    'FontSize',16,...
    'Max',5,...
    'Min',1,...
    'BackgroundColor',[0.8 1 0.8]);
man.list(3) = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.65 0.07 0.3 0.3],...
    'Style','listbox',...
    'String',num2str(allmz'),...
    'FontSize',16,...
    'Max',5,...
    'Min',1,...
    'BackgroundColor',[0.8 0.8 1]);

% A button to set the RGB image as the optical one
man.rgb2opt = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.02 0.9 0.025],...
    'Style','pushbutton',...
    'String','RGB > Opt',...
    'FontSize',10,...
    'BackgroundColor',[0 156 29]/256,...
    'ForegroundColor',[0 0 0]);

% A button to 'do' what we wanted...
man.do = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.5 0.9 0.1],...
    'Style','pushbutton',...
    'String','Update',...
    'FontSize',16,...
    'BackgroundColor',[0 156 29]/256,...
    'ForegroundColor',[0 0 0]);

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%