function desiHelp(src,event)
%desiHelp - simple function to draw a little gui to tell people to read the
%manual...


ss = get(0,'Screensize');
ss = ss / 2;

sz = [400 800];

pos = [ss(3)-(0.5*sz(1)) ss(4)-(0.5*sz(2)) sz(1) sz(2)];

ff = figure('Units','pixels','Position',pos,...
    'Toolbar','none',...
    'MenuBar','none',...
    'Name','desiHelp',...
    'Color','white');%[0.7 0.7 0.7]);

% Title...
uicontrol('Parent',ff,...
    'Units','normalized',...
    'Position',[0.05 0.9 0.9 0.075],...
    'Style','text',...
    'String','DESI Toolbox',...
    'FontSize',40,...
    'BackgroundColor','white');

% Get info from desiVersion
[v,d,f] = desiVersion;

% Version
uicontrol('Parent',ff,...
    'Units','normalized',...
    'Position',[0.05 0.85 0.9 0.03],...
    'Style','text',...
    'String',v,...
    'FontSize',18,...
    'BackgroundColor','white',...
    'HorizontalAlignment','center');

% Date
uicontrol('Parent',ff,...
    'Units','normalized',...
    'Position',[0.05 0.82 0.9 0.025],...
    'Style','text',...
    'String',d,...
    'FontSize',12,...
    'BackgroundColor','white',...
    'HorizontalAlignment','center');

% Description
uicontrol('Parent',ff,...
    'Units','normalized',...
    'Position',[0.05 0.79 0.9 0.025],...
    'Style','text',...
    'String',f,...
    'FontSize',12,...
    'BackgroundColor','white',...
    'HorizontalAlignment','center');


% Text box
uicontrol('Parent',ff,...
    'Units','normalized',...
    'Position',[0.05 0.55 0.9 0.2],...
    'Style','text',...
    'String',helpText,...
    'FontSize',16,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left');

% Text box
uicontrol('Parent',ff,...
    'Units','normalized',...
    'Position',[0.05 0.36 0.9 0.03],...
    'Style','text',...
    'String','Copy and paste the link below...',...
    'FontSize',16,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left');

% Documentation link
uicontrol('Parent',ff,...
    'Units','normalized',...
    'Position',[0.05 0.3 0.9 0.05],...
    'Style','edit',...
    'String',helpLink,...
    'FontSize',14,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left');

% Close
pb = uicontrol('Parent',ff,...
    'Units','normalized',...
    'Position',[0.05 0.05 0.9 0.05],...
    'Style','pushbutton',...
    'String','Close',...
    'FontSize',18);

set(pb,'Callback',{@closeWindow});

end

function [op] = helpText

op = ['Documentation for the toolbox can be found by following the '...
    'link below.  The documentation contains comprehensive help for '...
    'each of the functions available within the toolbox.  ' char(10)...
    'Should you find no answer to your query, then please '...
    'use the form (which is linked in the documentation) to get in '...
    'touch.  '];
end

function [op] = helpLink

op = 'https://docs.google.com/document/d/10xlzXTQH7_fdY7OFKjfRfiRlSDd5jVhqwqv_fdBAKxc/edit?usp=sharing';


clc

disp('**************************************************************************************************');
disp('**************************************************************************************************');
disp(char(10));
disp(op)
disp(char(10));
disp('**************************************************************************************************');
disp('**************************************************************************************************');



end

function closeWindow(~,~)

closereq

end