function desiStatistics(src,~,fig)
%desiStatistics - draw a stats window in the regulation space for plotting
%a few things...

% Get the guidata
dpn = guidata(fig.fig);
if isempty(dpn)
    return
end

% Can't draw this window without having done some annotations...
if ~isfield(dpn,'anno')
    disp('No annotations');
    set(src,'State','off');
    return
end

% The range of statistics is dependent on the data
if strcmp(dpn.mode,'single')
    listOfStats = {'PCA';'MMC-LOO';'MMC-k10';'Spectra';...
        'ANOVA';'Kruskal-Wallis';'Annotate';...
        'PCA-Unambig.';'MMC-Unambig.';'Annotation-Stats';...
        'Export'};
    
else
    listOfStats = {'PCA-IntPos';'PCA-IntNeg';...
        'MMC-IntPos';'MMC-IntNeg';...
        'PCA';'MMC';'Spectra';...
        'ANOVA';'Kruskal-Wallis';'Annotate'};
end

% Determine the range for results
range = [floor(min(dpn.d1.mz)) ceil(max(dpn.d1.mz))];

% Draw the window for the annotation manipulation...
[man] = manipulateWindow(fig,dpn,listOfStats,range);
if isempty(man)
    return;
end

% Set the callback for the finish button / window close
set(man.finish,'Callback',{@desiStatisticsDraw,fig,man});

% Callback for the fusion button...
if strcmp(dpn.mode,'dual')
    set(man.fuse,'Callback',{@fusionBoxCallback,man});
    fusionBoxCallback(man.fuse,[],man);
end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = manipulateWindow(fig,dpn,listOfStats,range)
% Window with the little options for manipulating the figure...

% This is where we draw everything
parent = fig.pan2;

fS = 14;

% Heading
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','Statistics',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);

%%%%

% Normalisation
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.85 0.5 0.1],...
    'Style','text',...
    'String','Normalisation',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.norm = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.85 0.5 0.1],...
    'Style','popupmenu',...
    'String',{'None','TIC','PQN-Mean','PQN-Median'},...
    'Value',2,...
    'FontSize',fS);

% Transformation
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.8 0.5 0.1],...
    'Style','text',...
    'String','Transformation',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.log = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.8 0.5 0.1],...
    'Style','popupmenu',...
    'String',{'None','Yes'},...
    'Value',2,...
    'FontSize',fS);

% Scaling
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.75 0.5 0.1],...
    'Style','text',...
    'String','Scaling',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.scale = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.75 0.5 0.1],...
    'Style','popupmenu',...
    'String',{'None','UV'},...
    'Value',1,...
    'FontSize',fS);

% m/z range...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.595-0.05 0.5 0.1],...
    'Style','text',...
    'String','m/z Range',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.mzL = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.66-0.05 0.23 0.04],...
    'Style','edit',...
    'String',num2str(range(1)),...
    'FontSize',fS);
man.mzH = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.74 0.66-0.05 0.23 0.04],...
    'Style','edit',...
    'String',num2str(range(2)),...
    'FontSize',fS);

% Potential options...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.525 0.5 0.05],...
    'Style','text',...
    'String','Analysis',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.list = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.375 0.475 0.2],...
    'Style','listbox',...
    'String',listOfStats,...
    'Value',1,...
    'FontSize',fS);%'Min',1,...'Max',3);

% Here we want an option for volcano/mz plotting of univariate results
man.volcano = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.37 0.4 0.025],...
    'Style','checkbox',...
    'String','UV: Volcano?',...
    'FontSize',13,...
    'Value',1,...
    'BackgroundColor',[1 1 1]);

% Here we want an option for volcano/mz plotting of univariate results
man.confmat = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.39 0.4 0.025],...
    'Style','checkbox',...
    'String','MMC: ConfMat?',...
    'FontSize',13,...
    'Value',0,...
    'BackgroundColor',[1 1 1]);

%%%%%

% Add a thing to decide on the method for fusion in polarity switched data.
% This just needs to be a popupmenu
if strcmp(dpn.mode,'dual')
    uicontrol('Parent',parent,...
        'Units','normalized',...
        'Position',[0 0.7 0.5 0.1],...
        'Style','text',...
        'String','Fusion',...
        'FontSize',fS,...
        'BackgroundColor',[1 1 1]);

    man.fuse = uicontrol('Parent',parent,...
        'Units','normalized',...
        'Position',[0.5 0.7 0.5 0.1],...
        'Style','popupmenu',...
        'String',{'LL (Concat)','HL (PCA #)','HL (PCA %)'},...
        'Value',2,...
        'FontSize',fS);
    
    man.fuseText = uicontrol('Parent',parent,...
        'Units','normalized',...
        'Position',[0 0.65 0.5 0.1],...
        'Style','text',...
        'String','PC number?',...
        'FontSize',fS,...
        'BackgroundColor',[1 1 1],...
        'Tag','hlfusion',...
        'Visible','off');

    man.fuseComp = uicontrol('Parent',parent,...
        'Units','normalized',...
        'Position',[0.52 0.65+0.065 0.45 0.04],...
        'Style','edit',...
        'String','10',...
        'FontSize',fS,...
        'Tag','hlfusion',...
        'Visible','off');
    
    % Retro projection of scores, and loadings plot options...
    uicontrol('Parent',parent,...
        'Units','normalized',...
        'Position',[0 0.65 0.5 0.05],...
        'Style','text',...
        'String','Retro projection',...
        'FontSize',fS,...
        'BackgroundColor',[1 1 1],...
        'Tag','hlfusion',...
        'Visible','off');
    
    man.retroScores = uicontrol('Parent',parent,...
        'Units','normalized',...
        'Position',[0.6 0.675 0.15 0.025],...
        'Style','checkbox',...
        'String','S',...
        'FontSize',fS,...
        'BackgroundColor',[1 1 1],...
        'Tag','hlfusion',...
        'Visible','off',...
        'Enable','on',...
        'Value',0);
    
    man.retroLoadings = uicontrol('Parent',parent,...
        'Units','normalized',...
        'Position',[0.775 0.675 0.15 0.025],...
        'Style','checkbox',...
        'String','L',...
        'FontSize',fS,...
        'BackgroundColor',[1 1 1],...
        'Tag','hlfusion',...
        'Visible','off',...
        'Value',1);



end



% Table of annotations...
unqCols = cell2mat(dpn.anno(:,2));
[~,b,~] = unique(unqCols);
tabDat = dpn.anno(b,[4 5]);
tabDat = [repmat({true},[size(tabDat,1) 1]) tabDat];
man.tab = uitable('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.1 0.9 0.25],...
    'ColumnName',{'?','Col','ID'},...
    'ColumnEditable',[true false false],...
    'FontSize',16,...
    'ColumnWidth',{40 40 100},...
    'Data',tabDat);

% Finish button
man.finish = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.01 0.9 0.05],...
    'Style','pushbutton',...
    'String','Analyse!',...
    'BackgroundColor',[0.5 0.9 0.5],...
    'FontSize',fS + 4);

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function fusionBoxCallback(src,~,man)
% Show and alter the fusion boxes if we have high level fusion...

% Find handle of all 'hlfusion'-tagged entries
f0 = findobj('Tag','hlfusion');

% Get the value of the actual box
val = get(src,'Value');
str = get(src,'String');
str = str{val};

switch lower(str(1:2))
    
    case 'hl'
        
        % Make the boxes visible
        set(f0,'Visible','on');
        
        % Change the title of the box depending on what kind of fusion...
        switch lower(str(4:end))
            case '(pca #)'
                txt = 'Number of PCs';
                val = '10';
                
            case '(pca %)'
                txt = '% of variance';
                val = '75';
                
            otherwise
                % There is no otherwise
                txt = 'I have no idea';
                val = 'Oranges';
        end
        set(man.fuseText,'String',txt);
        set(man.fuseComp,'String',val);
        
    otherwise
        % To include low level concatenation
        set(f0,'Visible','off');
        
end


end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%