function [ fig ] = desiDraw
%desiDraw - main function for drawing the window and the axes

f0 = findobj('Tag','desiposneg');
close(f0);

% Determine what layout is to be drawn on initialisation
fig.style = 'simple'; % simple | detail
locn = desiLocations(fig.style);

% Get a starting image?
dirIcon = deSlash([pwd filesep 'toolboxes/icons/']);
load([dirIcon filesep 'Images.mat']);
%idx = ceil(rand(1,1) * numel(images)); %#ok<USENS>

% Main figure
fig.fig = figure('Name','DESI Processing',...
    'Units','normalized',...
    'Position',[0.2 0.2 0.6 0.6],...
    'Tag','desiposneg',...
    'Color','white');

% A panel for holding the axes and stuff and then another to host all the
% menus instead of the pop up boxes. Quite a stretch I think
fig.pan1 = uipanel('Parent',fig.fig,...
    'Units','normalized',...
    'Position',[0.2 0 0.8 1],...
    'BackgroundColor','white');

fig.pan2 = uipanel('Parent',fig.fig,...
    'Units','normalized',...
    'Position',[0 0 0.2 1],...
    'BackgroundColor','white');

% Three axes - opt, ms1, ms2
fig.ax.opt(1) = axes('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.opt.ax,...
    'XTick',[],...
    'YTick',[],...
    'Box','off',...
    'Visible','on');
fig.ax.opt(2) = imagesc(ones(1,1,3));
set(fig.ax.opt(1),'LineWidth',5);

fig.ax.ms1(1) = axes('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.ms1.ax,...
    'XTick',[],...
    'YTick',[],...
    'Box','off',...
    'Visible','on');
fig.ax.ms1(2) = imagesc(ones(1,1,3));
set(fig.ax.ms1(1),'LineWidth',5);

% Another axes for showing mass spectra
fig.ax.sp(1) = axes('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.sp.ax,...
    'XTick',[],...
    'YTick',[],...
    'Box','on',...
    'Visible',locn.sp.vis,...
    'LineWidth',5,...
    'TickLength',[0 0]);
%fig.ax.sp(2) = imagesc(ones(1,1,3));
%set(fig.ax.sp(1),'LineWidth',5);


% And another for showing stuff like PCA of annotated pixels
fig.ax.mv(1) = axes('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.mv.ax,...
    'XTick',[],...
    'YTick',[],...
    'Box','on',...
    'Visible',locn.mv.vis,...
    'LineWidth',5,...
    'TickLength',[0 0]);
%fig.ax.mv(2) = imagesc(ones(1,1,3));
%set(fig.ax.mv(1),'LineWidth',5);

% Remove all labels from the axes
set([fig.ax.opt(1) fig.ax.ms1(1) fig.ax.sp(1) fig.ax.mv(1)],...
    'XTick',[],'YTick',[]);

% Titles for permanency
fig.titOpt = uicontrol('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.opt.lab1,...
    'Style','text',...
    'String','Optical',...
    'FontSize',20,...
    'FontWeight','bold',...
    'BackgroundColor','white');
fig.titPos = uicontrol('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.ms1.lab1,...
    'Style','text',...
    'String','DESI',...
    'FontSize',20,...
    'FontWeight','bold',...
    'BackgroundColor','white');

% Boxes somewhere for the pos / neg axes to tell the user what they are
% looking at. SUch as PCA image of PC1...
fig.txtOpt = uicontrol('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.opt.lab2,...
    'Style','text',...
    'String','---',...
    'FontSize',20,...
    'FontWeight','bold',...
    'BackgroundColor','white');
fig.txtPos = uicontrol('Parent',fig.pan1,...
    'Units','normalized',...
    'Position',locn.ms1.lab2,...
    'Style','text',...
    'String','---',...
    'FontSize',20,...
    'FontWeight','bold',...
    'BackgroundColor','white');



% Toolbar required
[fig] = desiDrawToolbar(fig);

end

