function [fig] = desiDrawToolbar(fig)

% Let's add a new toolbar to it instead of the horrible push buttons
fig.tb.main = uitoolbar('Parent',fig.fig,...
    'Tag','dpntb',...
    'Visible','on');

% Need to get the icons for the buttons...
dirIcon = deSlash([pwd filesep '/toolboxes/icons/']);

% Here a button for the loading a new file...
fig.tb.new = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'snowflake-2-48'),...
    'TooltipString','Pick an imzML file to be imported',...
    'Enable','on',...
    'Tag','desiSideMenu');

% Import QQQ data...
if ispc
    qqqEnable = 'on';
else
    qqqEnable = 'off';
end
fig.tb.qqq = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'letter-q-48 copy'),...
    'TooltipString','Import QQQ data - WINDOWS ONLY',...
    'Enable',qqqEnable);

% This will save the imported data to an HDF5 file
fig.tb.save = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'save-48'),...
    'TooltipString','Save processed data',...
    'Enable','on');

% Update the images...
fig.tb.refresh = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'refresh-2-48'),...
    'TooltipString','Update the ion image and start again...',...
    'Enable','on');

% Crop the MS image
fig.tb.crop = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'crop-2-48'),...
    'TooltipString','Crop the MS image permanently',...
    'Enable','on');

% Reprocess the file
fig.tb.reproc = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'clapperboard-48'),...
    'TooltipString','Reprocess the entire raw data',...
    'Enable','on');

% QC image for Waters data
fig.tb.qcImage = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'gavel-2-48'),...
    'TooltipString','Show the QC image',...
    'Enable','on');

% Raman images?
% if strcmp(getUser,'jmckenzi')
%     ramvis = 'on';
%     polyVis = 'on';
% else
%     ramvis = 'off';
%     polyVis = 'off';
% end
% fig.tb.raman = uipushtool('Parent',fig.tb.main,...
%     'CData',getImage(dirIcon,'audio-wave-48'),...
%     'TooltipString','Import Raman images',...
%     'Enable',ramvis);
% 
% % Polymer removal
% fig.tb.removePoly = uipushtool('Parent',fig.tb.main,...
%     'CData',getImage(dirIcon,'bottle-3-48'),...
%     'TooltipString','Remove polymeric signals',...
%     'Enable',polyVis);

% Flip up/down
% fig.tb.flipUD = uipushtool('Parent',fig.tb.main,...
%     'CData',getImage(dirIcon,'flip-vertical-48'),...
%     'TooltipString','Flip up/down',...
%     'Enable','on');

insertSeparator(fig.tb.main);

% Add an optical image
fig.tb.optimg = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'paper-clip-2-48'),...
    'TooltipString','Attach (!) an optical image',...
    'Enable','on');

% Change DESI ion image
fig.tb.editPos = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'edit-image-48'),...
    'TooltipString','MS image manipulation',...
    'Enable','on',...
    'Tag','desiSideMenu');

% Coregistration
fig.tb.coreg = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'photo-48'),...
    'TooltipString','Image coregistration',...
    'Enable','off',...
    'Tag','desiSideMenu');

% Fiducial markers
fig.tb.fiducial = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'point-objects-48'),...
    'TooltipString','Manual coregistration',...
    'Enable','off',...
    'Tag','desiSideMenu');

% Erase some lines from the (Waters) file
fig.tb.erase = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'erase-48'),...
    'TooltipString','Erase lines on (Waters) ion images',...
    'Enable','on',...
    'Tag','desiSideMenu');

% H&E visibility
fig.tb.hevis = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'eye-2-48'),...
    'TooltipString','Make the H&E image visible on the MS image',...
    'Enable','on',...
    'Tag','desiSideMenu');

insertSeparator(fig.tb.main);

% Zoom in
fig.tb.zoom(1) = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'zoom-in-2-48'),...
    'TooltipString','Zoom in',...
    'Enable','on');

% Zoom out
fig.tb.zoom(2) = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'zoom-out-2-48'),...
    'TooltipString','Zoom out',...
    'Enable','on');

% Zoom reset
fig.tb.zoomreset = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'resize-5-48'),...
    'TooltipString','Restore original zoom',...
    'Enable','on');

% Grid
fig.tb.grid = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'grid-48'),...
    'TooltipString','Grid',...
    'Enable','on');


insertSeparator(fig.tb.main);

% Annotation
fig.tb.annotate = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'brush-2-48'),...
    'TooltipString','Image annotation',...
    'Enable','on',...
    'Tag','desiSideMenu');

% Internal statistics
fig.tb.intStats = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'heat-map-48'),...
    'TooltipString','Quick and dirty statistics',...
    'Enable','on',...
    'Tag','desiSideMenu');

% Stats - or similar idea
% fig.tb.extract = uipushtool('Parent',fig.tb.main,...
%     'CData',getImage(dirIcon,'scatter-plot-48'),...
%     'TooltipString','Multivariate statistics',...
%     'Enable','on');

% Stats - or similar idea
fig.tb.segment = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'orange-48'),...
    'TooltipString','Multivariate segmentation (obvs)',...
    'Enable','on',...
    'Tag','desiSideMenu');

% Tissue outlines
% fig.tb.outline = uitoggletool('Parent',fig.tb.main,...
%     'CData',getImage(dirIcon,'circle-dashed-8-48'),...
%     'TooltipString','Tissue outlines',...
%     'Enable','on',...
%     'Tag','desiSideMenu');

insertSeparator(fig.tb.main);

% Window layout
if strcmp(fig.style,'detail')
    st = 'on';
else
    st = 'off';
end
fig.tb.layout = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'window-layout-48'),...
    'TooltipString','Change the window layout',...
    'Enable','on',...
    'State',st);

% Help button
fig.tb.help = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'question-mark-48'),...
    'TooltipString','Help');


%insertSeparator(fig.tb.main);

% Export figures
fig.tb.expfig = uipushtool('Parent',fig.tb.main,...
    'CData',fliplr(getImage(dirIcon,'stallion-48')),...
    'TooltipString','Neigh - figure extraction');

% Close other windows
fig.tb.duck = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'duck-48'),...
    'TooltipString','Quack - close other windows');

% What about enlarging the toolbar?
dpnEnlarge(fig.tb.main);

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [ico] = getImage(path,name)
% Get the necessary icon.  Need to beautify it a little bit more...

[ico] = importdata([path name '.png']);

[ico] = iconProcess(ico.alpha,ico.cdata);


end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function insertSeparator(h)

uipushtool('Parent',h,...
    'CData', NaN([50 50 3]),...
    'ClickedCallback',{},...
    'Separator', 'on',...
    'Tooltip','Is this button missing?');

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
