function desiOutlineWindow(src,event,fig)
%dpnSegmentationWindow - draw a window to allow us to play around with
%various segmentation things...

% Get the guidata
dpn = guidata(fig.fig);
if isempty(dpn)
    return
end

% Can't proceed without annotations
if ~isfield(dpn,'anno');
    disp('No annotations');
    set(src,'State','off');
    return
end

% Draw the segmentation window, which initially can feature things like
% PCA, and cluster analysis
[seg] = outlineWindow(src,event,fig);

% % Set the callbacks for the functions...
% switch dpn.mode
%     case 'dual'
%         set(seg.do,'Callback',{@dpnSegmentationPerform,fig,seg});
%     case 'single'
%         set(seg.do,'Callback',{@desiSegmentationPerform,fig,seg});
% end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = outlineWindow(src,event,fig)
% Window with the little options for manipulating the figure...

parent = fig.pan2;

% Opening text
man.tit = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','Outlines etc',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);

return

% Potential options...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.8 0.211 0.05],...
    'Style','text',...
    'String','Analysis',...
    'FontSize',16,...
    'BackgroundColor',[1 1 1]);
man.list = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.7 0.45 0.2],...
    'Style','listbox',...
    'String',{'PCA';'kMeans';'MMC'},...
    'Value',1,...
    'FontSize',16);%'Min',1,...'Max',3);

% What about a box for the normalisation to be performed
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.62 0.35 0.05],...
    'Style','text',...
    'String','Normalisation',...
    'FontSize',16,...
    'BackgroundColor',[1 1 1]);
man.norm = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.575 0.45 0.1],...
    'Style','popupmenu',...
    'String',{'None';'TIC';'PQN-Median';'PQN-Mean'},...
    'Value',1,...
    'FontSize',16);%'Min',1,...'Max',3);

% Remove background pixels?
man.remBG = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.575 0.9 0.05],...
    'Style','checkbox',...
    'String','Remove background pixels?',...
    'Value',1,...
    'FontSize',16,...
    'BackgroundColor',[1 1 1]);

% Log transformation?
man.doLog = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.54 0.9 0.05],...
    'Style','checkbox',...
    'String','Log transformation?',...
    'Value',0,...
    'FontSize',16,...
    'BackgroundColor',[1 1 1]);

% Range for low/high m/z range
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.4 0.48 0.2 0.05],...
    'Style','text',...
    'String','< m/z <',...
    'FontSize',12,...
    'BackgroundColor',[1 1 1]);
man.mzL = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.49 0.35 0.05],...
    'Style','edit',...
    'String','50',...
    'Value',1,...
    'FontSize',16);
man.mzH = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.6 0.49 0.35 0.05],...
    'Style','edit',...
    'String','2000',...
    'Value',1,...
    'FontSize',16);

% A box to limit k for kmeans
man.maxClust = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.2 0.7 0.15 0.025],...
    'Style','edit',...
    'String','4',...
    'Value',1,...
    'FontSize',16);
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.07 0.675 0.1 0.05],...
    'Style','text',...
    'String','k <= ',...
    'FontSize',14,...
    'BackgroundColor',[1 1 1]);



% A button to 'do' what we wanted...
man.do = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.4 0.9 0.05],...
    'Style','pushbutton',...
    'String','Go',...
    'FontSize',16,...
    'BackgroundColor',[0 156 29]/256,...
    'ForegroundColor',[0 0 0]);

% Rather than have buttons to flick through the images, I want instead to
% have three listboxes, one for Red/Green/Blue channels.  The user selects
% which colours go where
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.25 1 0.05],...
    'Style','text',...
    'String','Results',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);
man.res(1) = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.05 0.3 0.2],...
    'Style','listbox',...
    'String','',...
    'Value',1,...
    'FontSize',16,...
    'Min',1,...
    'Max',3,...
    'BackgroundColor',[1 0.8 0.8]);
man.res(2) = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.35 0.05 0.3 0.2],...
    'Style','listbox',...
    'String','',...
    'Value',1,...
    'FontSize',16,...
    'Min',1,...
    'Max',3,...
    'BackgroundColor',[0.8 1 0.8]);
man.res(3) = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.65 0.05 0.3 0.2],...
    'Style','listbox',...
    'String','',...
    'Value',1,...
    'FontSize',16,...
    'Min',1,...
    'Max',3,...
    'BackgroundColor',[0.8 0.8 1]);


% Buttons for flicking through images
% man.imgPrev = uicontrol('Parent',parent,...
%     'Units','normalized',...
%     'Position',[0.05 0 0.45 0.025],...
%     'Style','pushbutton',...
%     'String','Back',...
%     'FontSize',16);
% man.imgNext = uicontrol('Parent',parent,...
%     'Units','normalized',...
%     'Position',[0.5 0 0.45 0.025],...
%     'Style','pushbutton',...
%     'String','Forward',...
%     'FontSize',16);

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%