function desiFileUpload(~,~,fig,defP)
%desiFileUpload - this is the main function for starting to upload a file
%into the new DESI toolbox. This could be a saved file (mat/h5) or a new
%dataset to be processed, such as imzML or RAW.

% Close annotation / manipulation windows
f0 = findobj('Tag','manipulation');
close(f0);
f0 = findobj('Name','annotation');
close(f0);

% Change the layout to just the two window view...
xxxEnforceLayoutChange(fig,'single','off');

% Clear the axes... but what if we have annotation boxes?
sz = size(get(fig.ax.opt(2),'CData'));
set(fig.ax.opt(2),'CData',ones(sz));
sz = size(get(fig.ax.ms1(2),'CData'));
set(fig.ax.ms1(2),'CData',ones(sz));
f0 = findobj('Type','patch');
delete(f0);
f0 = findobj('Type','scatter');
delete(f0);

% Gather the guidata and determine the best path - if possible...
dpn = guidata(fig.fig);
if ~isempty(dpn)
    path = dpn.file.dir;
    if ~exist(path)
        path = defP;
    end
    sl = strfind(path,filesep);
    path = path(1:sl(end-1));
    if exist(path,'dir')
        defP = path;
    end
    
    % Change the polymer icon if we can...
    if isfield(dpn.d1,'poly')
        set(fig.tb.removePoly,'CData',dpn.d1.poly.icon.normal);
    end

end


% Need to turn the grid off too...
set(fig.tb.grid,'State','off');
desiGrid(fig.tb.grid,[],fig);

% Ask the user for a file
[file.nam,file.dir,flag] = uigetfile({'*.imzML; *.mat; *.dat; *.DAT; *.h5; *.txt'},...
    'File Select',defP);

% If no file selected, then quit/do nothing
if flag == 0
    set(fig.tb.new,'State','off');
    return
end

% Determine the file extension
file.ext = fileExtension(file.nam);

% Reformat the .dat files to the .raw file name instead
switch lower(file.ext)
    case 'dat'
        sl = strfind(file.dir,filesep);
        sl = sl(end-1);
        file.nam = file.dir(sl+1:end-1);
        file.dir = file.dir(1:sl);
        file.ext = 'raw';
end

% Traditionally we would display the options, but here instead we draw in
% the side menu...
        
% Get the options
%[opts,flag] = getOptions(file);
% [opts,flag] = desiGetProcOptions(file);
% if ~flag
%     return;
% end

% I want to display this in the menubar / figure title so that I know which
% file it is
set(fig.fig,'Name',['DESI Processing: ' file.nam]);

% Now decide what to do with it...
switch lower(file.ext)
    
    case {'imzml','raw'}

        
        %Draw the window for imzML / Raw files
        [man] = manipulateWindow(fig,file);
        set(man.finish,'Callback',{@desiFileProcess,fig,man,file,defP});
        set(man.method,'Callback',{@nzkSwitchOptions,man});
        
    case 'mat'
        % This is the option for reloading the saved files
        dpnMatlabLoad(file,fig);
        
    case 'h5'
        % This is the legacy support...will be difficult to get all the
        % structural elements...
        desiH5Load(fig,file,defP);
        
    case 'txt'
        % Analye files from raw files - potentially open to abuse and
        % failure
        desiWatersAnalyte(fig,file,defP);
        
    otherwise
        % Error - there are no other supported filetypes
end
      
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = manipulateWindow(fig,file)
% Window with the little options for manipulating the figure...

% Get the defaults
[opts,~] = desiGetProcOptions(file,'force');

% This is where we draw everything
parent = fig.pan2;

fS = 14;

% Heading
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','Processing',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);

%%%%

switch lower(file.ext)
    case 'imzml'
        methods = {'Normal';'Nazanin'};
        fileVal = 1;
        opts = opts.imzml;
        roi = 'off';
        nzk = 'off';
    case 'raw'
        methods = {'Centroid','Profile'};
        fileVal = 2;
        opts = opts.raw;
        roi = 'on';
        nzk = 'off';
end

% Filetype
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.85 0.5 0.1],...
    'Style','text',...
    'String','File Tpe',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.file = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.85 0.5 0.1],...
    'Style','popupmenu',...
    'String',{'imzML';'RAW'},...
    'Value',fileVal,...
    'FontSize',fS,...
    'Enable','off');

% Method
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.8 0.5 0.1],...
    'Style','text',...
    'String','Raw Data',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.method = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.8 0.5 0.1],...
    'Style','popupmenu',...
    'String',methods,...
    'Value',1,...
    'FontSize',fS);

% m/z range...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.595-0.05 0.5 0.1],...
    'Style','text',...
    'String','m/z Range',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.mzL = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.66-0.05 0.23 0.04],...
    'Style','edit',...
    'String',num2str(opts.mzRange(1)),...
    'FontSize',fS);
man.mzH = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.74 0.66-0.05 0.23 0.04],...
    'Style','edit',...
    'String',num2str(opts.mzRange(2)),...
    'FontSize',fS);

% m/z resolution...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.595-0.1 0.5 0.1],...
    'Style','text',...
    'String','m/z Resolution',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.mzRes = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.66-0.1 0.47 0.04],...
    'Style','edit',...
    'String',num2str(opts.mzRes),...
    'FontSize',fS);

% ppm shift...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.595-0.15 0.5 0.1],...
    'Style','text',...
    'String','ppm Shift',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.ppm = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.66-0.15 0.47 0.04],...
    'Style','edit',...
    'String',num2str(opts.ppmRes),...
    'FontSize',fS);

% mz fraction...
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.595-0.2 0.5 0.1],...
    'Style','text',...
    'String','m/z Fraction',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.mzFrac = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.66-0.2 0.47 0.04],...
    'Style','edit',...
    'String',num2str(opts.mzFrac),...
    'FontSize',fS);

% ROI
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.595-0.25 0.5 0.1],...
    'Style','text',...
    'String','ROI',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.roi = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.66-0.25 0.5 0.04],...
    'Style','popupmenu',...
    'String',{'Off';'On'},...
    'Value',1,...
    'FontSize',fS,...
    'Enable',roi);

% nzk Split correction
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.595-0.3 0.5 0.1],...
    'Style','text',...
    'String','Split Correction?',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.nzkSplCor = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.66-0.3 0.5 0.04],...
    'Style','popupmenu',...
    'String',{'No';'Yes'},...
    'Value',2,...
    'FontSize',fS,...
    'Enable',nzk);

% nkz bin length 1
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.595-0.35 0.5 0.1],...
    'Style','text',...
    'String','Bin Length 1?',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.nzkBL1 = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.66-0.35 0.5 0.04],...
    'Style','popupmenu',...
    'String',{'No';'Yes'},...
    'Value',1,...
    'FontSize',fS,...
    'Enable',nzk);

% nkz method
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.595-0.4 0.5 0.1],...
    'Style','text',...
    'String','Method',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.nzkMethod = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.66-0.4 0.5 0.04],...
    'Style','popupmenu',...
    'String',{'RG';'RM';'nn'},...
    'Value',3,...
    'FontSize',fS,...
    'Enable',nzk);


% Finish button
man.finish = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.01 0.9 0.05],...
    'Style','pushbutton',...
    'String','Import!',...
    'BackgroundColor',[0.5 0.9 0.5],...
    'FontSize',fS + 4);

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function nzkSwitchOptions(~,~,man)

% Determine the status
mt = man.method.String{man.method.Value};

switch mt
    
    case 'Normal'
        
        st1 = 'off';
        man.nzkSplCor.Enable = st1;
        man.nzkBL1.Enable = st1;
        man.nzkMethod.Enable = st1;
        
        st2 = 'on';
        man.mzRes.Enable = st2;
        
        
    case 'Nazanin'
        
        st1 = 'on';
        man.nzkSplCor.Enable = st1;
        man.nzkBL1.Enable = st1;
        man.nzkMethod.Enable = st1;
        
        st2 = 'off';
        man.mzRes.Enable = st2;

    otherwise
        % There is no otherwise
end

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

