function [fig] = dbDraw
% A function to draw the DB.  The inputs: files and unq come from the
% database file made in dbPopulate. This function will be run from there.

% Draw the window
set(0,'units','pixels');
fig.fig = figure('Name', 'desiDB', ...
    'Units', 'normalized', ...
    'Position',[0.25 0.25 0.5 0.5], ...
    'Tag', 'dbMain',...
    'Toolbar', 'none',...
    'Menubar','none',...
    'Color',[1 1 1]);

% This is a general service panel for options and stuff...
fig.panel = uipanel('Parent',fig.fig,...
    'Units','normalized',...
    'Position',[0.485 0.01 1-0.485-0.01 0.9],...
    'BackgroundColor',[1 1 1],...
    'Tag','uiTreePre');

% Add the table
fig.tab = uitable('Parent', fig.fig, ...
    'Units','normalized',...
    'Position', [0.01 0.01 0.465 0.9],...[0.01 0.01 0.98 0.9],...
    'FontUnits','pixels',...
    'FontSize',16,...
    'Tag','dbMainTable');

% Button to select all samples at once
fig.selAll = uicontrol('Parent',fig.fig,'Style','pushbutton', ...
    'String','All / None', ...
    'Units','normalized',...
    'Position', [0.01 0.915 0.04 0.03],...
    'TooltipString', 'Select all samples at once',...
    'Tag','dbselAll');

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
