function dbTableUpdate(fig,tabDat)
%dbTableUpdate - change the information in the table

set(fig.tab, 'Data', tabDat.data,...
    'ColumnName', tabDat.name, ...
    'ColumnFormat', tabDat.form, ...
    'ColumnEditable', tabDat.edit, ...
    'ColumnWidth', tabDat.wdth);

end

