function statsLoadingsPlot(parent,mz,loadings)
% PLot the loadings

f0 = get(parent,'Children');
delete(f0);

axes(parent);
hold on;

% Insert zeros...
%[x1,y1] = insertZeros(mz,loadings(:,1:2)',0.01);

% Apply an offset to make these visible
%y1(2,:) = y1(2,:) - (0.5 * max(y1(2,:))); 

%plot(mz,loadings(:,1:2));

stem(mz,loadings(:,1),...
    'MarkerSize',0.01,...
    'LineWidth',2,...
    'Color',[16 135 232]/256);

stem(mz,loadings(:,2),...
    'MarkerSize',0.01,...
    'LineWidth',2,...
    'Color',[230 115 142]/256);

set(gca,'XTick',0,...
    'XTickLabel',[],...
    'YTickLabel',[],...
    'YTick',0,...
    'LineWidth',5,...
    'TickLength',[0 0],...
    'YDir','normal');

grid off;

xlim([min(mz) max(mz)]);
ylim([min(loadings(:)) max(loadings(:))]);

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
