function statsExternalMenu(~,~,fig)
%statsExternalMenu - draw the menu for launching prediction of external
%samples, such as for the iKnife/Laser combination.

% Get the guidata
sts = guidata(fig.fig);
if isempty(sts)
    return
end

% Draw the window to help control the colours / groups / etc
[window] = manipulateWindow(fig,sts);


% Set the callback to generate the model - only one choice permitted so far
set(window.finish,'Callback',{@statsLDACalculate,fig,window});

% Select the external set of files
set(window.load,'Callback',{@statsExternalSelectFile,fig,window});

% Start!
set(window.classify,'Callback',{@statsExternalClassify,fig,window});

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = manipulateWindow(fig,sts)
% Window with the little options for manipulating the figure...

% This is where we draw everything
parent = fig.pan2;

fS = 14;

% Heading
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','Training Model',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);

%%%%

% Which DA to perform?
x = 0.9;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Model',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.analysis = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','popupmenu',...
    'String',{'MMC-Ext'},...
    'Value',1,...
    'FontSize',fS);

% Using which group / groups?
x = 0.85;
names = fieldnames(sts.proc.meta);
idx = strcmp(names,'hist');
if sum(idx) == 1
    idx = find(idx);
else
    idx = 1;
end
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Group(s)',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.groups = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','listbox',...
    'String',names,...
    'Value',idx,...
    'FontSize',fS,...
    'Min',1,...
    'Max',3);


% Analyse button
man.finish = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.70 0.4 0.05],...
    'Style','pushbutton',...
    'String','Generate Model',...
    'BackgroundColor',[0.5 0.9 0.5],...
    'FontSize',fS);


% Heading
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.60 1 0.05],...
    'Style','text',...
    'String','External Samples',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);

% Need to have a box to let us select the test set samples which are to be
% predicted...
man.load = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.55 0.4 0.05],...
    'Style','pushbutton',...
    'String','Select...',...
    'BackgroundColor',[0.9 0.9 0.5],...
    'FontSize',fS);

% Write out the file name
man.file = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 0.55 0.475 0.05],...
    'Style','text',...
    'String','',...
    'BackgroundColor',[1 1 1],...
    'FontSize',fS);

% How to classify the samples?
x = 0.40;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Classification',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.classMethod = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','popupmenu',...
    'String',{'k-nearest';'Centroid'},...
    'Value',2,...
    'FontSize',fS);

% How to classify the samples?
x = 0.45;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Comparison',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.classCompare = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','popupmenu',...
    'String','Unknown',...
    'Value',1,...
    'FontSize',fS,...
    'Enable','off');

% Analyse button
man.classify = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.35 0.9 0.05],...
    'Style','pushbutton',...
    'String','Begin',...
    'BackgroundColor',[0.5 0.9 0.9],...
    'FontSize',fS);


return


% Which components to plot
x = 0.45;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','LVs',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.comp1 = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.22 0.2],...
    'Style','listbox',...
    'String','NA',...
    'Value',1,...
    'FontSize',fS,...
    'BackgroundColor',[16 135 232]/256,...
    'ForegroundColor','white');%'Min',1,...'Max',3);
man.comp2 = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.75 x-0.15 0.22 0.2],...
    'Style','listbox',...
    'String','NA',...
    'Value',1,...
    'FontSize',fS,...
    'BackgroundColor',[230 115 142]/256,...
    'ForegroundColor','white');%'Min',1,...'Max',3);


% Do we want to draw the ellipses?
man.ellipse = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.35 0.4 0.025],...
    'Style','checkbox',...
    'String','Draw ellipses?',...
    'FontSize',fS,...
    'Value',0,...
    'BackgroundColor',[1 1 1]);


% What about showing stuff in the other axes?
x = 0.2;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Plot',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.extraPlot = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','popupmenu',...
    'String',{'Confusion'},...
    'Value',1,...
    'FontSize',fS);%'Min',1,...'Max',3);

% Some kind of option for font size
x = 0.17;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Font size',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.fontSize = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x+0.025 0.475 0.02],...
    'Style','edit',...
    'String','24',...
    'FontSize',fS);%'Min',1,...'Max',3);

% Some kind of option for marker size
x = 0.14;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Marker size',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.markerSize = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x+0.025 0.475 0.02],...
    'Style','edit',...
    'String','300',...
    'FontSize',fS);%'Min',1,...'Max',3);

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
