function statsLDAMenu(~,~,fig)
%statsLDAMenu - perform discriminants analysis. Probs just focus on
%MMC, LDA, and PLS-DA, maybe with a bit of regression eventually

% Get the guidata
sts = guidata(fig.fig);
if isempty(sts)
    return
end

% Draw the window to help control the colours / groups / etc
[window] = manipulateWindow(fig,sts);

% Set the callback for the finish button
set(window.finish,'Callback',{@statsLDACalculate,fig,window});

% Callbacks that do the drawing
set(window.comp1,'Callback',{@statsLDADraw,fig,window});
set(window.comp2,'Callback',{@statsLDADraw,fig,window});
set(window.ellipse,'Callback',{@statsLDADraw,fig,window});
set(window.colgroup,'Callback',{@statsLDADraw,fig,window});

set(window.groups,'Callback',{@updateColGroup,window.colgroup});

set(window.extraPlot,'Callback',{@statsLDAExtra,fig,window});
set(window.fontSize,'Callback',{@statsLDAExtra,fig,window});
set(window.markerSize,'Callback',{@statsLDAExtra,fig,window});

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = manipulateWindow(fig,sts)
% Window with the little options for manipulating the figure...

% This is where we draw everything
parent = fig.pan2;

fS = 14;

% Heading
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','Discriminants Analyses',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);

%%%%

% Which DA to perform?
x = 0.9;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Analysis',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.analysis = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','popupmenu',...
    'String',{'MMC-LOO';'MMC-k10';'MMC-LPO';'MMC-Ext'},...
    'Value',3,...
    'FontSize',fS);

% Using which group / groups?
x = 0.85;
names = fieldnames(sts.proc.meta);
idx = strcmp(names,'hist') | strcmp(names,'histID');
if sum(idx) == 1
    idx = find(idx);
else
    idx = 1;
end
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Group(s)',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.groups = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','listbox',...
    'String',names,...
    'Value',idx,...
    'FontSize',fS,...
    'Min',1,...
    'Max',3);

% Which group to use for CV?
x = 0.65;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','CV group',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.cvgroup = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','popupmenu',...
    'String',names,...
    'Value',1,...
    'FontSize',fS);

% Analyse button
man.finish = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.60 0.9 0.05],...
    'Style','pushbutton',...
    'String','Discriminate!',...
    'BackgroundColor',[0.5 0.9 0.5],...
    'FontSize',fS + 4);


% Which components to plot
x = 0.45;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','LVs',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.comp1 = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.22 0.2],...
    'Style','listbox',...
    'String','NA',...
    'Value',1,...
    'FontSize',fS,...
    'BackgroundColor',[16 135 232]/256,...
    'ForegroundColor','white');%'Min',1,...'Max',3);
man.comp2 = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.75 x-0.15 0.22 0.2],...
    'Style','listbox',...
    'String','NA',...
    'Value',1,...
    'FontSize',fS,...
    'BackgroundColor',[230 115 142]/256,...
    'ForegroundColor','white');%'Min',1,...'Max',3);


% Do we want to draw the ellipses?
man.ellipse = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.35 0.4 0.025],...
    'Style','checkbox',...
    'String','Draw ellipses?',...
    'FontSize',fS,...
    'Value',0,...
    'BackgroundColor',[1 1 1]);

% Which group to use for CV?
x = 0.250;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Colour group',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.colgroup = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','popupmenu',...
    'String',names,...
    'Value',idx,...
    'FontSize',fS);



% What about showing stuff in the other axes?
x = 0.15;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Plot',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.extraPlot = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','popupmenu',...
    'String',{'Confusion'},...
    'Value',1,...
    'FontSize',fS);%'Min',1,...'Max',3);

% Some kind of option for font size
x = 0.13;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Font size',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.fontSize = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x+0.025 0.475 0.02],...
    'Style','edit',...
    'String','24',...
    'FontSize',fS);%'Min',1,...'Max',3);

% Some kind of option for marker size
x = 0.10;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Marker size',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.markerSize = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x+0.025 0.475 0.02],...
    'Style','edit',...
    'String','300',...
    'FontSize',fS);%'Min',1,...'Max',3);


% ROC
man.roc = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.025 0.25 0.025],...
    'Style','pushbutton',...
    'String','ROC',...
    'BackgroundColor',[0.8 0.2 0.8],...
    'FontSize',fS,...
    'Visible','off');

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function updateColGroup(src,~,grp)

grp.Value = src.Value;

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
