function [fig] = statsToolbarDraw(fig)

% Let's add a new toolbar to it instead of the horrible push buttons
fig.tb.main = uitoolbar('Parent',fig.fig,...
    'Tag','statstb',...
    'Visible','on');

% Need to get the icons for the buttons...
dirIcon = deSlash([pwd filesep 'toolboxes/icons/']);

% Here a button for the loading a new file...
fig.tb.open = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'envelope-open-48'),...
    'TooltipString','Open some data',...
    'Enable','on');

% Import data from the workspace
fig.tb.import = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'data-transfer-download-48'),...
    'TooltipString','Import from workspace',...
    'Enable','on');

% Import data from the workspace
fig.tb.save = uipushtool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'save-as-48'),...
    'TooltipString','Save current progress',...
    'Enable','on');

insertSeparator(fig.tb.main);

% Display the table of metadata in here...
fig.tb.table = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'list-48'),...
    'TooltipString','Metadata viewer',...
    'Enable','on');

insertSeparator(fig.tb.main);

% Norm/tran/scal
fig.tb.norm = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'math-48'),...
    'TooltipString','Normalise, transform, etc...',...
    'Enable','on',...
    'Tag','statsSideMenu');

insertSeparator(fig.tb.main);

% Here a button for the loading a new file...
% fig.tb.statsMV = uitoggletool('Parent',fig.tb.main,...
%     'CData',getImage(dirIcon,'scatter-plot-48'),...
%     'TooltipString','Multivariate statistics',...
%     'Enable','on',...
%     'Tag','statsSideMenu');
% 
% insertSeparator(fig.tb.main);
% insertSeparator(fig.tb.main);

%% UNIVARIATE
% ANOVA, KW, etc
fig.tb.doUnivariate = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'bar-chart-5-48'),...
    'TooltipString','Univariate analysis',...
    'Enable','on',...
    'Tag','statsSideMenu');

fig.tb.doBoxplots = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'filled-box-48'),...
    'TooltipString','Draw boxplots',...
    'Enable','on',...
    'Tag','statsSideMenu');

% Ratio analysis
fig.tb.doRatio = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'divide-2-48'),...
    'TooltipString','Ratio analysis',...
    'Enable','on',...
    'Tag','statsSideMenu');

insertSeparator(fig.tb.main);

%% MULTIVARIATE - unsuper
% Here a button for the loading a new file...
fig.tb.doPCA = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'cupcake-3-48'),...
    'TooltipString','cuPCAke - now you see it, you want to bring me one',...
    'Enable','on',...
    'Tag','statsSideMenu');

% Here a button for the loading a new file...
fig.tb.doClust = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'tree-structure-48'),...
    'TooltipString','Cluster analyses',...
    'Enable','off',...
    'Tag','statsSideMenu');

if strcmp(getUser,'jmckenzi')
    tmpEnable = 'on';
else
    tmpEnable = 'off';
end
fig.tb.doTSNE = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'pear-48'),...
    'TooltipString','tSNE',...
    'Enable',tmpEnable,...
    'Tag','statsSideMenu');

insertSeparator(fig.tb.main);

%% MULTIVARIATE - super
% Here a button for the loading a new file...
fig.tb.doLDA = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'line-2-48'),...
    'TooltipString','Linear discriminants analyses',...
    'Enable','on',...
    'Tag','statsSideMenu');


% External samples
fig.tb.doExternal = uitoggletool('Parent',fig.tb.main,...
    'CData',getImage(dirIcon,'test-tube-2-48'),...
    'TooltipString','External samples',...
    'Enable','off',...
    'Tag','statsSideMenu');




% Annotation
% fig.tb.doAnnotation = uitoggletool('Parent',fig.tb.main,...
%     'CData',getImage(dirIcon,'edit-9-48'),...
%     'TooltipString','Annotation of features',...
%     'Enable','on',...
%     'Tag','statsSideMenu');

% What about enlarging the toolbar?
dpnEnlarge(fig.tb.main);

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [ico] = getImage(path,name)
% Get the necessary icon.  Need to beautify it a little bit more...

[ico] = importdata([path name '.png']);

[ico] = iconProcess(ico.alpha,ico.cdata);

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function insertSeparator(h)

uipushtool('Parent',h,...
    'CData', NaN([50 50 3]),...
    'ClickedCallback',{},...
    'Separator', 'on',...
    'Tooltip','Is this button missing?');

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
