function statsUnivariateMenu(~,~,fig)
%statsUnivariateMenu - menu for drawing / displaying univariate results

% Get the guidata
sts = guidata(fig.fig);
if isempty(sts)
    return
end

% Draw the window to help control the colours / groups / etc
[window] = manipulateWindow(fig,sts);

% Set the callback for the finish button
set(window.finish,'Callback',{@statsUnivariateCalculate,fig,window});

% Functions to draw the results...
set(window.draw,'Callback',{@statsUnivariateDraw,fig,window});

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = manipulateWindow(fig,sts)
% Window with the little options for manipulating the figure...

% This is where we draw everything
parent = fig.pan2;

fS = 14;

% Heading
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','Univariate Analyses',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);

%%%%

% Which DA to perform?
if strcmp(getUser,'jmckenzi')
    mtds = {'ANOVA';'Kruskal-Wallis';'Output';'Text Output'};
else
    mtds = {'ANOVA';'Kruskal-Wallis';'Text Output'};
end
x = 0.9;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Analysis',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.analysis = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','popupmenu',...
    'String',mtds,...
    'Value',1,...
    'FontSize',fS);

% Using which group / groups?
x = 0.85;
names = fieldnames(sts.proc.meta);
idx = strcmp(names,'hist');
if sum(idx) == 1
    idx = find(idx);
else
    idx = 1;
end
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Group(s)',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.groups = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','listbox',...
    'String',names,...
    'Value',idx,...
    'FontSize',fS,...
    'Min',1,...
    'Max',3);

% Analyse button
man.finish = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.60 0.9 0.05],...
    'Style','pushbutton',...
    'String','Calculate!',...
    'BackgroundColor',[0.5 0.9 0.5],...
    'FontSize',fS + 4);


%%%%%

% Sub Heading
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.3 1 0.05],...
    'Style','text',...
    'String','Plot Options',...
    'FontSize',20,...
    'BackgroundColor',[1 1 1]);


% Plot P or Q values?
x = 0.225;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Group(s)',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.plotPQ = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15+0.15 0.475 0.05],...
    'Style','listbox',...
    'String',{'p values';'q values'},...
    'Value',idx,...
    'FontSize',fS);

% Some kind of option for font size
x = 0.17;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','p/q Value',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.pqThresh = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x+0.025 0.475 0.02],...
    'Style','edit',...
    'String','0.05',...
    'FontSize',fS);%'Min',1,...'Max',3);

% Some kind of option for marker size
x = 0.14;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','-log2 Fold Change',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.fcThresh = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x+0.025 0.475 0.02],...
    'Style','edit',...
    'String','1',...
    'FontSize',fS);%'Min',1,...'Max',3);


% Draw button
man.draw = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.1 0.9 0.05],...
    'Style','pushbutton',...
    'String','Draw',...
    'BackgroundColor',[0.9 0.5 0.9],...
    'FontSize',fS + 4);

return


% Which group to use for CV?
x = 0.65;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','CV group',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.cvgroup = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','popupmenu',...
    'String',names,...
    'Value',1,...
    'FontSize',fS);



% Which components to plot
x = 0.45;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','LVs',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.comp1 = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.22 0.2],...
    'Style','listbox',...
    'String','NA',...
    'Value',1,...
    'FontSize',fS,...
    'BackgroundColor',[16 135 232]/256,...
    'ForegroundColor','white');%'Min',1,...'Max',3);
man.comp2 = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.75 x-0.15 0.22 0.2],...
    'Style','listbox',...
    'String','NA',...
    'Value',1,...
    'FontSize',fS,...
    'BackgroundColor',[230 115 142]/256,...
    'ForegroundColor','white');%'Min',1,...'Max',3);


% Do we want to draw the ellipses?
man.ellipse = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.35 0.4 0.025],...
    'Style','checkbox',...
    'String','Draw ellipses?',...
    'FontSize',fS,...
    'Value',0,...
    'BackgroundColor',[1 1 1]);


% What about showing stuff in the other axes?
x = 0.2;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Plot',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.extraPlot = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','popupmenu',...
    'String',{'Confusion'},...
    'Value',1,...
    'FontSize',fS);%'Min',1,...'Max',3);

% Some kind of option for font size
x = 0.17;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Font size',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.fontSize = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x+0.025 0.475 0.02],...
    'Style','edit',...
    'String','24',...
    'FontSize',fS);%'Min',1,...'Max',3);

% Some kind of option for marker size
x = 0.14;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Marker size',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.markerSize = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x+0.025 0.475 0.02],...
    'Style','edit',...
    'String','300',...
    'FontSize',fS);%'Min',1,...'Max',3);

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
