function statsMultivariateMenu(~,~,fig)
%desiStatistics - draw a stats window in the regulation space for plotting
%a few things...

% Get the guidata
sts = guidata(fig.fig);
if isempty(sts)
    return
end

% The range of statistics is dependent on the data
listOfStats = {'PCA';'MMC-LOO';'MMC-k10';...
    'ANOVA';'Kruskal-Wallis';'Annotate'};

% Draw the window for the annotation manipulation...
[window] = manipulateWindow(fig,sts,listOfStats);
if isempty(window)
    return;
end

% Set the callback for the finish button / window close
%set(man.finish,'Callback',{@statsMultivariateCalculate,fig,window});

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [man] = manipulateWindow(fig,sts,listOfStats)
% Window with the little options for manipulating the figure...

% This is where we draw everything
parent = fig.pan2;

fS = 14;

% Heading
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 0.95 1 0.05],...
    'Style','text',...
    'String','Statistics',...
    'FontSize',24,...
    'BackgroundColor',[1 1 1]);

%%%%

% Potential options...
x = 0.9;
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Analysis',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.list = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','listbox',...
    'String',listOfStats,...
    'Value',1,...
    'FontSize',fS);%'Min',1,...'Max',3);

% Here we want an option for volcano/mz plotting of univariate results
man.volcano = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.75 0.4 0.025],...
    'Style','checkbox',...
    'String','UV: Volcano?',...
    'FontSize',13,...
    'Value',1,...
    'BackgroundColor',[1 1 1]);

% Here we want an option for volcano/mz plotting of univariate results
man.confmat = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.77 0.4 0.025],...
    'Style','checkbox',...
    'String','MMC: ConfMat?',...
    'FontSize',13,...
    'Value',0,...
    'BackgroundColor',[1 1 1]);

% Need to make a window for the meta groups to be listed here...
x = 0.600;
names = fieldnames(sts.proc.meta);
uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0 x 0.5 0.05],...
    'Style','text',...
    'String','Groups',...
    'FontSize',fS,...
    'BackgroundColor',[1 1 1]);
man.groups = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.5 x-0.15 0.475 0.2],...
    'Style','listbox',...
    'String',names,...
    'Value',1,...
    'FontSize',fS);%'Min',1,...'Max',3);



% Table of annotations...
% unqCols = cell2mat(dpn.anno(:,2));
% [~,b,~] = unique(unqCols);
% tabDat = dpn.anno(b,[4 5]);
% tabDat = [repmat({true},[size(tabDat,1) 1]) tabDat];
% man.tab = uitable('Parent',parent,...
%     'Units','normalized',...
%     'Position',[0.05 0.1 0.9 0.25],...
%     'ColumnName',{'?','Col','ID'},...
%     'ColumnEditable',[true false false],...
%     'FontSize',16,...
%     'ColumnWidth',{40 40 100},...
%     'Data',tabDat);

% Finish button
man.finish = uicontrol('Parent',parent,...
    'Units','normalized',...
    'Position',[0.05 0.01 0.9 0.05],...
    'Style','pushbutton',...
    'String','Analyse!',...
    'BackgroundColor',[0.5 0.9 0.5],...
    'FontSize',fS + 4);

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
